/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import uk.co.boots.columbus.cmdb.model.dto.EnvironmentConfigDTO;
import uk.co.boots.columbus.cmdb.model.dto.EnvironmentConfigDTOService;
import uk.co.boots.columbus.cmdb.model.dto.support.PageRequestByExample;
import uk.co.boots.columbus.cmdb.model.dto.support.PageResponse;
import uk.co.boots.columbus.cmdb.model.repository.EnvironmentConfigRepository;
import uk.co.boots.columbus.cmdb.model.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/environmentConfigs")
public class EnvironmentConfigResource {

    private final Logger log = LoggerFactory.getLogger(EnvironmentConfigResource.class);

    @Inject
    private EnvironmentConfigRepository environmentConfigRepository;
    @Inject
    private EnvironmentConfigDTOService environmentConfigDTOService;

    /**
     * Create a new EnvironmentConfig.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<EnvironmentConfigDTO> create(@RequestBody EnvironmentConfigDTO environmentConfigDTO) throws URISyntaxException {

        log.debug("Create EnvironmentConfigDTO : {}", environmentConfigDTO);

        if (environmentConfigDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create EnvironmentConfig with existing ID").body(null);
        }

        EnvironmentConfigDTO result = environmentConfigDTOService.save(environmentConfigDTO);

        return ResponseEntity.created(new URI("/api/environmentConfigs/" + result.id)).body(result);
    }

    /**
    * Find by id EnvironmentConfig.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<EnvironmentConfigDTO> findById(@PathVariable Long id) throws URISyntaxException {

        log.debug("Find by id EnvironmentConfig : {}", id);

        return Optional.ofNullable(environmentConfigDTOService.findOne(id))
                .map(environmentConfigDTO -> new ResponseEntity<>(environmentConfigDTO, HttpStatus.OK)).orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update EnvironmentConfig.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<EnvironmentConfigDTO> update(@RequestBody EnvironmentConfigDTO environmentConfigDTO) throws URISyntaxException {

        log.debug("Update EnvironmentConfigDTO : {}", environmentConfigDTO);

        if (!environmentConfigDTO.isIdSet()) {
            return create(environmentConfigDTO);
        }

        EnvironmentConfigDTO result = environmentConfigDTOService.save(environmentConfigDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of EnvironmentConfig using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<EnvironmentConfigDTO>> findAll(@RequestBody PageRequestByExample<EnvironmentConfigDTO> prbe) throws URISyntaxException {
        PageResponse<EnvironmentConfigDTO> pageResponse = environmentConfigDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<EnvironmentConfigDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<EnvironmentConfigDTO> results = environmentConfigDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id ${}entity.model.type}.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Long id) throws URISyntaxException {

        log.debug("Delete by id EnvironmentConfig : {}", id);

        try {
            environmentConfigRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}