/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import uk.co.boots.columbus.cmdb.model.dto.ServerTypeDTO;
import uk.co.boots.columbus.cmdb.model.dto.ServerTypeDTOService;
import uk.co.boots.columbus.cmdb.model.dto.support.PageRequestByExample;
import uk.co.boots.columbus.cmdb.model.dto.support.PageResponse;
import uk.co.boots.columbus.cmdb.model.repository.ServerTypeRepository;
import uk.co.boots.columbus.cmdb.model.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/serverTypes")
public class ServerTypeResource {

    private final Logger log = LoggerFactory.getLogger(ServerTypeResource.class);

    @Inject
    private ServerTypeRepository serverTypeRepository;
    @Inject
    private ServerTypeDTOService serverTypeDTOService;

    /**
     * Create a new ServerType.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ServerTypeDTO> create(@RequestBody ServerTypeDTO serverTypeDTO) throws URISyntaxException {

        log.debug("Create ServerTypeDTO : {}", serverTypeDTO);

        if (serverTypeDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create ServerType with existing ID").body(null);
        }

        ServerTypeDTO result = serverTypeDTOService.save(serverTypeDTO);

        return ResponseEntity.created(new URI("/api/serverTypes/" + result.id)).body(result);
    }

    /**
    * Find by id ServerType.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ServerTypeDTO> findById(@PathVariable Long id) throws URISyntaxException {

        log.debug("Find by id ServerType : {}", id);

        return Optional.ofNullable(serverTypeDTOService.findOne(id)).map(serverTypeDTO -> new ResponseEntity<>(serverTypeDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update ServerType.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ServerTypeDTO> update(@RequestBody ServerTypeDTO serverTypeDTO) throws URISyntaxException {

        log.debug("Update ServerTypeDTO : {}", serverTypeDTO);

        if (!serverTypeDTO.isIdSet()) {
            return create(serverTypeDTO);
        }

        ServerTypeDTO result = serverTypeDTOService.save(serverTypeDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of ServerType using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<ServerTypeDTO>> findAll(@RequestBody PageRequestByExample<ServerTypeDTO> prbe) throws URISyntaxException {
        PageResponse<ServerTypeDTO> pageResponse = serverTypeDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<ServerTypeDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<ServerTypeDTO> results = serverTypeDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id ${}entity.model.type}.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Long id) throws URISyntaxException {

        log.debug("Delete by id ServerType : {}", id);

        try {
            serverTypeRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}