/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.server.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.*;

import uk.co.boots.columbus.cmdb.model.server.domain.Server;
import uk.co.boots.columbus.cmdb.model.server.domain.ServerConfig;
import uk.co.boots.columbus.cmdb.model.server.domain.ServerConfig_;

public interface ServerConfigRepository extends JpaRepository<ServerConfig, Long> {

	List<ServerConfig> findByServerName(String envName);
    List<ServerConfig>findByServer_nodeSubEnvironments_subEnvironment_environment_name(String name);
    List<ServerConfig>findDistinctByServer_nodeSubEnvironments_subEnvironment_environment_id(Long id);
    List<ServerConfig> findByServer_name(String typeName);
    Page<ServerConfig> findByServer_id(Pageable pageRequest);

	default List<ServerConfig> complete(String query, int maxResults) {
        ServerConfig probe = new ServerConfig();
        probe.setParameter(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(ServerConfig_.parameter.getName(), match -> match.ignoreCase().startsWith());

        Page<ServerConfig> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}