/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.server.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.*;

import uk.co.boots.columbus.cmdb.model.server.domain.ServerType;
import uk.co.boots.columbus.cmdb.model.server.domain.ServerType_;

public interface ServerTypeRepository extends JpaRepository<ServerType, Long> {

    /**
     * Return the persistent instance of {@link ServerType} with the given unique property value name,
     * or null if there is no such persistent instance.
     *
     * @param name the unique value
     * @return the corresponding {@link ServerType} persistent instance or null
     */
    ServerType getByName(String name);

    default List<ServerType> complete(String query, int maxResults) {
        ServerType probe = new ServerType();
        probe.setName(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(ServerType_.name.getName(), match -> match.ignoreCase().contains());

        Page<ServerType> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}