/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.golbalconfig.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Globalconfig.class)
public abstract class Globalconfig_ {

    // Raw attributes
    public static volatile SingularAttribute<Globalconfig, Long> id;
    public static volatile SingularAttribute<Globalconfig, String> parameter;
    public static volatile SingularAttribute<Globalconfig, String> value;
    public static volatile SingularAttribute<Globalconfig, String> hieraAddress;
}