/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.environment.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;

import uk.co.boots.columbus.cmdb.model.hiera.dto.CoreConfigDTO;

/**
 * Simple DTO for EnvironmentConfig.
 */
public class EnvironmentConfigDTO implements CoreConfigDTO{
    public Long getId() {
		return id;
	}

	public String getParameter() {
		return parameter;
	}

	public String getValue() {
		return value;
	}

	public String getHieraAddress() {
		return hieraAddress;
	}

    public Long id;
    public String parameter;
    public String value;
    public String hieraAddress;
    public EnvironmentDTO environment;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
    
	@Override
	public void setParameter(String param) {
		this.parameter = param;
	}

	@Override
	public void setValue(String val) {
		this.value = val;
	}

	@Override
	public void setHieraAddress(String addr) {
		this.hieraAddress = addr;
	}
    
}