/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.environment.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(EnvironmentConfig.class)
public abstract class EnvironmentConfig_ {

    // Raw attributes
    public static volatile SingularAttribute<EnvironmentConfig, Long> id;
    public static volatile SingularAttribute<EnvironmentConfig, String> parameter;
    public static volatile SingularAttribute<EnvironmentConfig, String> value;
    public static volatile SingularAttribute<EnvironmentConfig, String> hieraAddress;

    // Many to one
    public static volatile SingularAttribute<EnvironmentConfig, Environment> environment;
}