/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.packageinfo.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.*;

import uk.co.boots.columbus.cmdb.model.packageinfo.domain.PackageType;
import uk.co.boots.columbus.cmdb.model.packageinfo.domain.PackageType_;

public interface PackageTypeRepository extends JpaRepository<PackageType, Long> {

    /**
     * Return the persistent instance of {@link PackageType} with the given unique property value name,
     * or null if there is no such persistent instance.
     *
     * @param name the unique value
     * @return the corresponding {@link PackageType} persistent instance or null
     */
    PackageType getByName(String name);

    default List<PackageType> complete(String query, int maxResults) {
        PackageType probe = new PackageType();
        probe.setName(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(PackageType_.name.getName(), match -> match.ignoreCase().startsWith());

        Page<PackageType> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}