/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.release.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.*;

import uk.co.boots.columbus.cmdb.model.release.domain.ReleaseData;
import uk.co.boots.columbus.cmdb.model.release.domain.ReleaseData_;

public interface ReleaseDataRepository extends JpaRepository<ReleaseData, Long> {

    default List<ReleaseData> complete(String query, int maxResults) {
        ReleaseData probe = new ReleaseData();
        probe.setParam(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(ReleaseData_.param.getName(), match -> match.ignoreCase().startsWith());

        Page<ReleaseData> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}