/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.domain;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.google.common.base.MoreObjects;

@Entity
@Table(name = "cm_environmentconfig")
public class EnvironmentConfig implements Identifiable<Long>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(EnvironmentConfig.class.getName());

    // Raw attributes
    private Long id;
    private String parameter;
    private String value;
    private String hieraAddress;

    // Many to one
    private Environment environment;

    @Override
    public String entityClassName() {
        return EnvironmentConfig.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "EnvConfigID", precision = 19)
    @GeneratedValue
    @Id
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public EnvironmentConfig id(Long id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [parameter] ------------------------

    @Size(max = 50)
    @Column(name = "EnvConfigParameter", length = 50)
    public String getParameter() {
        return parameter;
    }

    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    public EnvironmentConfig parameter(String parameter) {
        setParameter(parameter);
        return this;
    }
    // -- [value] ------------------------

    @Size(max = 50)
    @Column(name = "EnvConfigValue", length = 50)
    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public EnvironmentConfig value(String value) {
        setValue(value);
        return this;
    }
    // -- [hieraAddress] ------------------------

    @Size(max = 50)
    @Column(name = "EnvConfigHieraAddress", length = 50)
    public String getHieraAddress() {
        return hieraAddress;
    }

    public void setHieraAddress(String hieraAddress) {
        this.hieraAddress = hieraAddress;
    }

    public EnvironmentConfig hieraAddress(String hieraAddress) {
        setHieraAddress(hieraAddress);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: EnvironmentConfig.environment ==> Environment.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "EnvironmentID", nullable = false)
    @ManyToOne
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * Set the {@link #environment} without adding this EnvironmentConfig instance on the passed {@link #environment}
     */
    public void setEnvironment(Environment environment) {
        this.environment = environment;
    }

    public EnvironmentConfig environment(Environment environment) {
        setEnvironment(environment);
        return this;
    }

    /**
     * Apply the default values.
     */
    public EnvironmentConfig withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof EnvironmentConfig && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this, parameter + value + hieraAddress);
    }

    /**
     * Construct a readable string representation for this EnvironmentConfig instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("parameter", getParameter()) //
                .add("value", getValue()) //
                .add("hieraAddress", getHieraAddress()) //
                .toString();
    }
}