/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(PackageInfo.class)
public abstract class PackageInfo_ {

    // Raw attributes
    public static volatile SingularAttribute<PackageInfo, Long> id;
    public static volatile SingularAttribute<PackageInfo, String> name;

    // Many to one
    public static volatile SingularAttribute<PackageInfo, PackageType> packageType;
    public static volatile SingularAttribute<PackageInfo, ServerType> serverType;
    public static volatile SingularAttribute<PackageInfo, Release> release;
}