/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.packageinfo.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import uk.co.boots.columbus.cmdb.model.core.dto.support.PageRequestByExample;
import uk.co.boots.columbus.cmdb.model.core.dto.support.PageResponse;
import uk.co.boots.columbus.cmdb.model.core.rest.support.AutoCompleteQuery;
import uk.co.boots.columbus.cmdb.model.packageinfo.dto.PackageTypeDTO;
import uk.co.boots.columbus.cmdb.model.packageinfo.dto.PackageTypeDTOService;
import uk.co.boots.columbus.cmdb.model.packageinfo.repository.PackageTypeRepository;

@RestController
@RequestMapping("/api/packageTypes")
public class PackageTypeResource {

    private final Logger log = LoggerFactory.getLogger(PackageTypeResource.class);

    @Inject
    private PackageTypeRepository packageTypeRepository;
    @Inject
    private PackageTypeDTOService packageTypeDTOService;

    /**
     * Create a new PackageType.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PackageTypeDTO> create(@RequestBody PackageTypeDTO packageTypeDTO) throws URISyntaxException {

        log.debug("Create PackageTypeDTO : {}", packageTypeDTO);

        if (packageTypeDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create PackageType with existing ID").body(null);
        }

        PackageTypeDTO result = packageTypeDTOService.save(packageTypeDTO);

        return ResponseEntity.created(new URI("/api/packageTypes/" + result.id)).body(result);
    }

    /**
    * Find by id PackageType.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PackageTypeDTO> findById(@PathVariable Long id) throws URISyntaxException {

        log.debug("Find by id PackageType : {}", id);

        return Optional.ofNullable(packageTypeDTOService.findOne(id)).map(packageTypeDTO -> new ResponseEntity<>(packageTypeDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update PackageType.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PackageTypeDTO> update(@RequestBody PackageTypeDTO packageTypeDTO) throws URISyntaxException {

        log.debug("Update PackageTypeDTO : {}", packageTypeDTO);

        if (!packageTypeDTO.isIdSet()) {
            return create(packageTypeDTO);
        }

        PackageTypeDTO result = packageTypeDTOService.save(packageTypeDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of PackageType using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<PackageTypeDTO>> findAll(@RequestBody PageRequestByExample<PackageTypeDTO> prbe) throws URISyntaxException {
        PageResponse<PackageTypeDTO> pageResponse = packageTypeDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<PackageTypeDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<PackageTypeDTO> results = packageTypeDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id ${}entity.model.type}.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Long id) throws URISyntaxException {

        log.debug("Delete by id PackageType : {}", id);

        try {
            packageTypeRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}