/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.release.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import uk.co.boots.columbus.cmdb.model.core.dto.support.PageRequestByExample;
import uk.co.boots.columbus.cmdb.model.core.dto.support.PageResponse;
import uk.co.boots.columbus.cmdb.model.core.rest.support.AutoCompleteQuery;
import uk.co.boots.columbus.cmdb.model.release.dto.ReleaseDataDTO;
import uk.co.boots.columbus.cmdb.model.release.dto.ReleaseDataDTOService;
import uk.co.boots.columbus.cmdb.model.release.repository.ReleaseDataRepository;

@RestController
@RequestMapping("/api/releaseDatas")
public class ReleaseDataResource {

    private final Logger log = LoggerFactory.getLogger(ReleaseDataResource.class);

    @Inject
    private ReleaseDataRepository releaseDataRepository;
    @Inject
    private ReleaseDataDTOService releaseDataDTOService;

    /**
     * Create a new ReleaseData.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ReleaseDataDTO> create(@RequestBody ReleaseDataDTO releaseDataDTO) throws URISyntaxException {

        log.debug("Create ReleaseDataDTO : {}", releaseDataDTO);

        if (releaseDataDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create ReleaseData with existing ID").body(null);
        }

        ReleaseDataDTO result = releaseDataDTOService.save(releaseDataDTO);

        return ResponseEntity.created(new URI("/api/releaseDatas/" + result.id)).body(result);
    }

    /**
    * Find by id ReleaseData.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ReleaseDataDTO> findById(@PathVariable Long id) throws URISyntaxException {

        log.debug("Find by id ReleaseData : {}", id);

        return Optional.ofNullable(releaseDataDTOService.findOne(id)).map(releaseDataDTO -> new ResponseEntity<>(releaseDataDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update ReleaseData.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ReleaseDataDTO> update(@RequestBody ReleaseDataDTO releaseDataDTO) throws URISyntaxException {

        log.debug("Update ReleaseDataDTO : {}", releaseDataDTO);

        if (!releaseDataDTO.isIdSet()) {
            return create(releaseDataDTO);
        }

        ReleaseDataDTO result = releaseDataDTOService.save(releaseDataDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of ReleaseData using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<ReleaseDataDTO>> findAll(@RequestBody PageRequestByExample<ReleaseDataDTO> prbe) throws URISyntaxException {
        PageResponse<ReleaseDataDTO> pageResponse = releaseDataDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<ReleaseDataDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<ReleaseDataDTO> results = releaseDataDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id ${}entity.model.type}.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Long id) throws URISyntaxException {

        log.debug("Delete by id ReleaseData : {}", id);

        try {
            releaseDataRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}