/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.environment.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import uk.co.boots.columbus.cmdb.model.core.dto.support.PageRequestByExample;
import uk.co.boots.columbus.cmdb.model.core.dto.support.PageResponse;
import uk.co.boots.columbus.cmdb.model.core.rest.support.AutoCompleteQuery;
import uk.co.boots.columbus.cmdb.model.environment.dto.SubEnvironmentConfigDTO;
import uk.co.boots.columbus.cmdb.model.environment.dto.SubEnvironmentConfigDTOService;
import uk.co.boots.columbus.cmdb.model.environment.repository.SubEnvironmentConfigRepository;

@RestController
@RequestMapping("/api/subEnvironmentConfigs")
public class SubEnvironmentConfigResource {

    private final Logger log = LoggerFactory.getLogger(SubEnvironmentConfigResource.class);

    private SubEnvironmentConfigRepository subEnvironmentConfigRepository;
    @Inject
    private SubEnvironmentConfigDTOService subEnvironmentConfigDTOService;

    /**
     * Create a new EnvironmentConfig.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<SubEnvironmentConfigDTO> create(@RequestBody SubEnvironmentConfigDTO subEnvironmentConfigDTO) throws URISyntaxException {

        log.debug("Create SubEnvironmentConfigDTO : {}", subEnvironmentConfigDTO);

        if (subEnvironmentConfigDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create EnvironmentConfig with existing ID").body(null);
        }

        SubEnvironmentConfigDTO result = subEnvironmentConfigDTOService.save(subEnvironmentConfigDTO);

        return ResponseEntity.created(new URI("/api/environmentConfigs/" + result.id)).body(result);
    }

    /**
    * Find by id EnvironmentConfig.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<SubEnvironmentConfigDTO> findById(@PathVariable Long id) throws URISyntaxException {

        log.debug("Find by id SubEnvironmentConfig : {}", id);

        return Optional.ofNullable(subEnvironmentConfigDTOService.findOne(id, 2))
                .map(subEnvironmentConfigDTO -> new ResponseEntity<>(subEnvironmentConfigDTO, HttpStatus.OK)).orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update EnvironmentConfig.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<SubEnvironmentConfigDTO> update(@RequestBody SubEnvironmentConfigDTO subEnvironmentConfigDTO) throws URISyntaxException {

        log.debug("Update SubEnvironmentConfigDTO : {}", subEnvironmentConfigDTO);

        if (!subEnvironmentConfigDTO.isIdSet()) {
            return create(subEnvironmentConfigDTO);
        }

        SubEnvironmentConfigDTO result = subEnvironmentConfigDTOService.save(subEnvironmentConfigDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of EnvironmentConfig using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<SubEnvironmentConfigDTO>> findAll(@RequestBody PageRequestByExample<SubEnvironmentConfigDTO> prbe) throws URISyntaxException {
        PageResponse<SubEnvironmentConfigDTO> pageResponse = subEnvironmentConfigDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<SubEnvironmentConfigDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<SubEnvironmentConfigDTO> results = subEnvironmentConfigDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id ${}entity.model.type}.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Long id) throws URISyntaxException {

        log.debug("Delete by id EnvironmentConfig : {}", id);

        try {
            subEnvironmentConfigRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}