/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.component.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;
import javax.persistence.OptimisticLockException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import uk.co.boots.columbus.cmdb.model.component.dto.ComponentConfigDTO;
import uk.co.boots.columbus.cmdb.model.component.dto.ComponentConfigDTOService;
import uk.co.boots.columbus.cmdb.model.component.repository.ComponentConfigRepository;
import uk.co.boots.columbus.cmdb.model.core.dto.support.PageRequestByExample;
import uk.co.boots.columbus.cmdb.model.core.dto.support.PageResponse;
import uk.co.boots.columbus.cmdb.model.core.rest.support.AutoCompleteQuery;
import uk.co.boots.columbus.cmdb.model.core.rest.support.CsvResponse;
import uk.co.boots.columbus.cmdb.model.hiera.dto.HieraDTO;

@RestController
@RequestMapping("/api/componentConfigs")
public class ComponentConfigResource {

    private final Logger log = LoggerFactory.getLogger(ComponentConfigResource.class);

    @Inject
    private ComponentConfigRepository componentConfigRepository;
    @Inject
    private ComponentConfigDTOService componentConfigDTOService;

    /**
     * Create a new ComponentConfig.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ComponentConfigDTO> create(@RequestBody ComponentConfigDTO componentConfigDTO) throws URISyntaxException {

        log.debug("Create ComponentConfigDTO : {}", componentConfigDTO);

        if (componentConfigDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create ComponentConfig with existing ID").body(null);
        }

        ComponentConfigDTO result = componentConfigDTOService.save(componentConfigDTO);

        return ResponseEntity.created(new URI("/api/componentConfigs/" + result.id)).body(result);
    }
    
    /**
    * Find by id ComponentConfig.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ComponentConfigDTO> findById(@PathVariable Long id) throws URISyntaxException {

        log.debug("Find by id ComponentConfig : {}", id);

        return Optional.ofNullable(componentConfigDTOService.findOne(id)).map(componentConfigDTO -> new ResponseEntity<>(componentConfigDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update ComponentConfig.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ComponentConfigDTO> update(@RequestBody ComponentConfigDTO componentConfigDTO) throws URISyntaxException, OptimisticLockException{

        log.debug("Update ComponentConfigDTO : {}", componentConfigDTO);

        if (!componentConfigDTO.isIdSet()) {
            return create(componentConfigDTO);
        }

        ComponentConfigDTO result = componentConfigDTOService.save(componentConfigDTO);


        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of ComponentConfig using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<ComponentConfigDTO>> findAll(@RequestBody PageRequestByExample<ComponentConfigDTO> prbe) throws URISyntaxException {
        PageResponse<ComponentConfigDTO> pageResponse = componentConfigDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<ComponentConfigDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<ComponentConfigDTO> results = componentConfigDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id ${}entity.model.type}.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Long id) throws URISyntaxException {

        log.debug("Delete by id ComponentConfig : {}", id);

        try {
            componentConfigRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}