/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.server.domain;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

import uk.co.boots.columbus.cmdb.model.environment.domain.Environment;
import uk.co.boots.columbus.cmdb.model.node.domain.Node;

@StaticMetamodel(Server.class)
public abstract class Server_ {

    // Raw attributes
    public static volatile SingularAttribute<Server, Long> id;
    public static volatile SingularAttribute<Server, String> name;

    // Many to one
    public static volatile SingularAttribute<Server, ServerType> serverType;
 
    // One to Many
    public static volatile ListAttribute<Server, ServerConfig> serverConfigs;
     
}