/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.dto;

import java.util.List;
import java.util.stream.Collectors;

import javax.inject.Inject;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import uk.co.boots.columbus.cmdb.model.domain.Environment;
import uk.co.boots.columbus.cmdb.model.domain.Server;
import uk.co.boots.columbus.cmdb.model.domain.ServerType;
import uk.co.boots.columbus.cmdb.model.dto.support.PageRequestByExample;
import uk.co.boots.columbus.cmdb.model.dto.support.PageResponse;
import uk.co.boots.columbus.cmdb.model.repository.EnvironmentRepository;
import uk.co.boots.columbus.cmdb.model.repository.ServerRepository;
import uk.co.boots.columbus.cmdb.model.repository.ServerTypeRepository;

/**
 * A simple DTO Facility for Server.
 */
@Service
public class ServerDTOService {

    @Inject
    private ServerRepository serverRepository;
    @Inject
    private ServerTypeDTOService serverTypeDTOService;
    @Inject
    private ServerTypeRepository serverTypeRepository;
    @Inject
    private EnvironmentDTOService environmentDTOService;
    @Inject
    private EnvironmentRepository environmentRepository;
    
    @Transactional(readOnly = true)
    public ServerDTO findOne(Long id) {
        return toDTO(serverRepository.findOne(id));
    }

    @Transactional(readOnly = true)
    public List<ServerDTO> complete(String query, int maxResults) {
        List<Server> results = serverRepository.complete(query, maxResults);
        return results.stream().map(this::toDTO).collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public PageResponse<ServerDTO> findAll(PageRequestByExample<ServerDTO> req) {
        Example<Server> example = null;
        Server server = toEntity(req.example);

        if (server != null) {
            example = Example.of(server);
        }

        Page<Server> page;
        if (example != null) {
            page = serverRepository.findAll(example, req.toPageable());
        } else {
            page = serverRepository.findAll(req.toPageable());
        }

        List<ServerDTO> content = page.getContent().stream().map(this::toDTO).collect(Collectors.toList());
        return new PageResponse<>(page.getTotalPages(), page.getTotalElements(), content);
    }

    /**
     * Save the passed dto as a new entity or update the corresponding entity if any.
     */
    @Transactional
    public ServerDTO save(ServerDTO dto) {

    	if (dto == null) {
            return null;
        }

        Server server;
        if (dto.isIdSet()) {
            server = serverRepository.findOne(dto.id);
        } else {
            server = new Server();
        }

        server.setName(dto.name);

        if (dto.serverType == null) {
            server.setServerType(null);
        } else {
            ServerType serverType = server.getServerType();
            if (serverType == null || (serverType.getId().compareTo(dto.serverType.id) != 0)) {
                server.setServerType(serverTypeRepository.findOne(dto.serverType.id));
            }
        }

        if (dto.environment == null) {
            server.setEnvironment(null);
        } else {
            Environment environment = server.getEnvironment();
            if (environment == null || (environment.getId().compareTo(dto.environment.id) != 0)) {
                server.setEnvironment(environmentRepository.findOne(dto.environment.id));
            }
        }

        return toDTO(serverRepository.save(server));
    }

    /**
     * Converts the passed server to a DTO.
     */
    public ServerDTO toDTO(Server server) {
        return toDTO(server, 1);
    }

    /**
     * Converts the passed server to a DTO. The depth is used to control the
     * amount of association you want. It also prevents potential infinite serialization cycles.
     *
     * @param server
     * @param depth the depth of the serialization. A depth equals to 0, means no x-to-one association will be serialized.
     *              A depth equals to 1 means that xToOne associations will be serialized. 2 means, xToOne associations of
     *              xToOne associations will be serialized, etc.
     */
    public ServerDTO toDTO(Server server, int depth) {
        if (server == null) {
            return null;
        }

        ServerDTO dto = new ServerDTO();

        dto.id = server.getId();
        dto.name = server.getName();
        if (depth-- > 0) {
            dto.serverType = serverTypeDTOService.toDTO(server.getServerType(), depth);
            dto.environment = environmentDTOService.toDTO(server.getEnvironment(), depth);
        }

        return dto;
    }

    /**
     * Converts the passed dto to a Server.
     * Convenient for query by example.
     */
    public Server toEntity(ServerDTO dto) {
        return toEntity(dto, 1);
    }

    /**
     * Converts the passed dto to a Server.
     * Convenient for query by example.
     */
    public Server toEntity(ServerDTO dto, int depth) {
        if (dto == null) {
            return null;
        }

        Server server = new Server();

        server.setId(dto.id);
        server.setName(dto.name);
        if (depth-- > 0) {
            server.setServerType(serverTypeDTOService.toEntity(dto.serverType, depth));
            server.setEnvironment(environmentDTOService.toEntity(dto.environment, depth));
        }

        return server;
    }
}