/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.component.domain;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.google.common.base.MoreObjects;

import uk.co.boots.columbus.cmdb.model.core.domain.Identifiable;
import uk.co.boots.columbus.cmdb.model.core.domain.IdentifiableHashBuilder;

@Entity
@Table(name = "cm_componentconfig")
public class ComponentConfig implements Identifiable<Long>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(ComponentConfig.class.getName());

    // Raw attributes
    private Long id;
    private String parameter;
    private String value;
    private String hieraAddress;

    // Many to one
    private SolutionComponent solutionComponent;

    @Override
    public String entityClassName() {
        return ComponentConfig.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "CompConfigID", precision = 19)
    @GeneratedValue
    @Id
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public ComponentConfig id(Long id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [parameter] ------------------------

    @Size(max = 50)
    @Column(name = "CompConfigParameter", length = 50)
    public String getParameter() {
        return parameter;
    }

    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    public ComponentConfig parameter(String parameter) {
        setParameter(parameter);
        return this;
    }
    // -- [value] ------------------------

    @Size(max = 50)
    @Column(name = "CompConfigValue", length = 50)
    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public ComponentConfig value(String value) {
        setValue(value);
        return this;
    }
    // -- [hieraAddress] ------------------------

    @Size(max = 50)
    @Column(name = "CompConfigHieraAddress", length = 50)
    public String getHieraAddress() {
        return hieraAddress;
    }

    public void setHieraAddress(String hieraAddress) {
        this.hieraAddress = hieraAddress;
    }

    public ComponentConfig hieraAddress(String hieraAddress) {
        setHieraAddress(hieraAddress);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: ComponentConfig.my_component ==> SolutionComponent.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "ComponentID", nullable = false)
    @ManyToOne
    public SolutionComponent getSolutionComponent() {
        return solutionComponent;
    }

    /**
     * Set the {@link #solutionComponent} without adding this ComponentConfig instance on the passed {@link #solutionComponent}
     */
    public void setSolutionComponent(SolutionComponent solutionComponent) {
        this.solutionComponent = solutionComponent;
    }

    public ComponentConfig my_component(SolutionComponent solutionComponent) {
        setSolutionComponent(solutionComponent);
        return this;
    }

    /**
     * Apply the default values.
     */
    public ComponentConfig withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof ComponentConfig && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this, parameter + value + hieraAddress);
    }

    /**
     * Construct a readable string representation for this ComponentConfig instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("parameter", getParameter()) //
                .add("value", getValue()) //
                .add("hieraAddress", getHieraAddress()) //
                .toString();
    }
}