/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.component.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

import uk.co.boots.columbus.cmdb.model.packageinfo.domain.PackageInfo;

@StaticMetamodel(SolutionComponent.class)
public abstract class SolutionComponent_ {

    // Raw attributes
    public static volatile SingularAttribute<SolutionComponent, Long> id;
    public static volatile SingularAttribute<SolutionComponent, String> name;

    // Many to one
    public static volatile SingularAttribute<SolutionComponent, PackageInfo> packageInfo;
}