/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.release.domain;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

import uk.co.boots.columbus.cmdb.model.core.domain.Identifiable;
import uk.co.boots.columbus.cmdb.model.environment.domain.SubEnvironment;

@Entity
@Table(name = "cm_release")
public class Release implements Identifiable<Long>, Serializable {
	private static final long serialVersionUID = 1L;
	private static final Logger log = Logger.getLogger(Release.class.getName());

	@Column(name = "ReleaseID", precision = 19)
	@GeneratedValue
	@Id
	private Long id;

	@NotEmpty
	@Size(max = 50)
	@Column(name = "ReleaseName", nullable = false, unique = true, length = 50)
	private String name;

	// bi-directional many-to-one association to ReleaseConfig
	@OneToMany(mappedBy = "release")
	private List<ReleaseConfig> releaseConfigs;

	// bi-directional many-to-one association to ReleaseData
	@OneToMany(mappedBy = "release")
	private List<ReleaseData> releaseData;

	// bi-directional many-to-one association to SubEnvironment
	@OneToMany(mappedBy = "release")
	private List<SubEnvironment> subEnvironments;

	@Transient
	private volatile int previousHashCode = 0;

	@Override
	public String entityClassName() {
		return Release.class.getSimpleName();
	}

	// -- [id] ------------------------

	@Override
	public Long getId() {
		return id;
	}

	@Override
	public void setId(Long id) {
		this.id = id;
	}

	@Override
	@Transient
	public boolean isIdSet() {
		return id != null;
	}
	// -- [name] ------------------------

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Equals implementation using a business key.
	 */
	@Override
	public boolean equals(Object other) {
		return this == other || (other instanceof Release && hashCode() == other.hashCode());
	}

	@Override
	public int hashCode() {
		int hashCode = Objects.hashCode(getName());

		if (previousHashCode != 0 && previousHashCode != hashCode) {
			log.warning("DEVELOPER: hashCode has changed!." //
					+ "If you encounter this message you should take the time to carefuly review equals/hashCode for: " //
					+ getClass().getCanonicalName());
		}

		previousHashCode = hashCode;
		return hashCode;
	}

	/**
	 * Construct a readable string representation for this Release instance.
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return MoreObjects.toStringHelper(this) //
				.add("id", getId()) //
				.add("name", getName()) //
				.toString();
	}
}