/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.release.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(ReleaseData.class)
public abstract class ReleaseData_ {

    // Raw attributes
    public static volatile SingularAttribute<ReleaseData, String> param;
    public static volatile SingularAttribute<ReleaseData, String> value;
    public static volatile SingularAttribute<ReleaseData, Long> id;

    // Many to one
    public static volatile SingularAttribute<ReleaseData, Release> release;
    public static volatile SingularAttribute<ReleaseData, ReleaseDataType> dataType;
}