/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package uk.co.boots.columbus.cmdb.model.component.dto;

import uk.co.boots.columbus.cmdb.model.core.dto.BaseDTO;
import uk.co.boots.columbus.cmdb.model.core.dto.LockableDTO;
import uk.co.boots.columbus.cmdb.model.packageinfo.dto.PackageInfoDTO;

/**
 * Simple DTO for SolutionComponent.
 */
public class SolutionComponentDTO extends BaseDTO implements LockableDTO{
    public String name;
    public PackageInfoDTO packageInfo;
}